# Generated by Django 3.0.8 on 2020-07-24 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ip_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(max_length=30, verbose_name='IP Adres')),
                ('activity', models.BooleanField(verbose_name='Durum')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
